---
- hosts: all
  vars:
  - ubuntu_release: raring
  - logwatch_email: logwatch@goncalopereira.com
  - files_path: roles/boot/files
  - tasks_path: roles/boot/tasks
  - handlers_path: roles/boot/handlers
    
  tasks:  
  - include: $tasks_path/apt.yml tasks_path=$tasks_path

  - name: Install ufw
    action: apt pkg=ufw state=installed

  - include: $tasks_path/logging.yml
  - include: $tasks_path/apt.yml
  - include: $tasks_path/ssh.yml
 
  - name: Enable ufw
    action: shell echo 'y' | ufw enable
 
  handlers:
  - include: $handlers_path/ssh.yml
