# bootstrap.yml
 
---
- hosts: all
  vars:
  - ubuntu_release: raring
  - logwatch_email: logwatch@goncalopereira.com
  - files_path: roles/boot/files
  - tasks_path: roles/boot/tasks
    
  - include: $tasks_path/apt.yml tasks_path=$tasks_path
  
  tasks:  
  - include: $tasks_path/apt.yml tasks_path=$tasks_path
  
  - name: Disallow password authentication
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify: Restart ssh
 
  - name: Install logwatch
    action: apt pkg=logwatch state=installed
 
  - name: Make logwatch mail $logwatch_email daily
    action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present create=yes
 
  - name: Install ufw
    action: apt pkg=ufw state=installed

  - name: Setup ufw for ssh
    action: shell ufw allow $item/tcp
    with_items: [ 22, 443 ]
 
  - name: Enable ufw
    action: shell echo 'y' | ufw enable

  - name: Install fail2ban
    action: apt pkg=fail2ban state=installed

  - name: Install psad
    action: apt pkg=psad state=installed

  - name: Start psad
    action: shell iptables -A INPUT -j LOG

  handlers:
  - name: Restart ssh
    action: service name=ssh state=restarted
