- hosts: all
  vars: 
    - pythondev_version: 2.7.3-0ubuntu2.2
    - pip_version:  1.0-1build1
    - skyline_version: master
    - skyline_path:  /srv/skyline

  tasks:
    - name: Install python dev $pythondev_version
      action: apt pkg=python-dev=$pythondev_version state=installed

    - name: Install pip $pip_version
      action: apt pkg=python-pip=$pip_version state=installed

    - name: Checkout Skyline 
      action: git repo=https://github.com/etsy/skyline.git dest=$skyline_path version=$skyline_version

    - name: Install requirements.txt with pip
      action: pip name=$item.name version=$item.version
      with_items:
        - { name: 'redis', version: '2.7.2' }
        - { name: 'hiredis', version: '0.1.1' }
        - { name: 'python-daemon', version: '1.6' }
        - { name: 'flask', version: '0.9' }
        - { name: 'simplejson', version: '2.0.9' }
        - { name: 'unittest2' }
        - { name: 'mock' }

