- hosts: all
  vars: 
    - skyline_version: master
    - skyline_path:  /srv/skyline

  tasks:
    - name: Install tools
      action: apt pkg={{ item.name }}={{ item.version }} state=installed
      with_items: 
        - { name: python-dev, version: 2.7.3-0ubuntu2.2 }
        - { name: python-pip, version: 1.0-1build1 }

    - name: Checkout Skyline 
      action: git repo=https://github.com/etsy/skyline.git dest={{ skyline_path }} version={{ skyline_version }}

    - name: Install {{ skyline_path }}/requirements.txt with pip
      action: pip requirements=$skyline_path/requirements.txt

    - name: Install remaining dependencies with pip
      action: pip name={{ item.name }}
      with_items:
        - { name: patsy, version: 0.2.1 }
        - { name: msgpack_python, version: 0.4.0 }

    - name: Install python dependencies
      action: apt pkg={{ item.name }}={{ item.version }} state=installed
      with_items: 
        - { name: python-numpy, version: '1:1.6.1-6ubuntu1' }
        - { name: python-scipy, version: 0.9.0+dfsg1-1ubuntu2 }
        - { name: python-scikits.statsmodels, version: 0.3.1-3ubuntu1 }