- hosts: all
  vars: 
    - skyline: {
      version: master,
      path: /srv/skyline,
      repo: 'https://github.com/etsy/skyline.git' }
    - redis_server: { name: redis-server, version: '2:2.6.13-1' }
    - graphite: { url: 'http://localhost', carbon_port: 2003 }
    - webapp: { port: 1500, ip: 0.0.0.0 }
    - horizon: { pickle_port: 2024, udp_port: 2025 }
    - oculus: { url: 'http://your_oculus_host.com' }

  tasks:
    - name: Install tools
      action: apt pkg={{ item.name }} state=installed
      with_items: 
        - { name: python-dev }
        - { name: python-pip }
        - { name: git }

    - name: Checkout Skyline 
      action: git repo={{ skyline.repo }} dest={{ skyline.path }} version={{ skyline.version }}

    - name: Create Skyline log directories
      action: file path={{ item }} state=directory
      with_items: [ /var/log/skyline, /var/run/skyline ]

    - name: Install {{ skyline.path }}/requirements.txt with pip
      action: pip requirements={{ skyline.path }}/requirements.txt

    - name: Install remaining dependencies with pip
      action: pip name={{ item.name }} version={{ item.version }}
      with_items:
        - { name: patsy, version: 0.2.1 }
        - { name: msgpack_python, version: 0.4.0 }

    - name: Install python dependencies
      action: apt pkg={{ item.name }} state=installed
      with_items: 
        - { name: python-numpy }
        - { name: python-scipy }
        - { name: python-scikits.statsmodels }

    - name: Install redis
      action: apt pkg={{ redis_server.name }}={{ redis_server.version }} state=installed
      notify: restart redis

    - name: Update redis.conf
      action: copy src=roles/skyline/files/redis.conf dest=/etc/redis/redis.conf
      notify: restart redis

    - name: Update Skyline settings.py template
      template: src=roles/skyline/templates/settings.py.j2 dest={{ skyline.path }}/src/settings.py
      notify: 
        - kill python
        - start skyline

  handlers:
    - name: restart redis
      action: service name={{ redis_server.name }} state=restarted

    - name: kill python #no way to know if apps run...
      command: "pkill -9 python"
    - name: start skyline
      command: "{{ skyline.path }}/bin/{{ item }} start"
      with_items: [ horizon.d, analyzer.d, webapp.d ]