---
- hosts: all
  vars:
    - user: goncalo  
    - config_path: roles/user
  tasks:
  - name: Add user
    action: user name=$user

  - name: Add authorized key
    action: authorized_key user=$user key='$FILE($config_path/$item)'
    with_items: [ 7d_id_rsa.pub, gh_id_rsa.pub, gp_id_rsa.pub ]
  
  - name: Add user to sudoers
    action: lineinfile dest=/etc/sudoers regexp="$user ALL" line="$user ALL=(ALL) NOPASSWD:ALL" state=present

  - name: Install vim
    action: apt pkg=vim state=installed

  - name: Install zsh
    action: apt pkg=zsh state=installed

  - name: Add zsh to $user
    shell: chsh -s /bin/zsh $user
     
  - name: Add byobu to $user
    action: apt pkg=byobu state=installed

  - name: Install ruby
    action: apt pkg=ruby state=installed

  - name: Install rubygems
    action: apt pkg=rubygems state=installed

  - name: Install homesick
    action: gem name=homesick state=latest

  - name: Install git
    action: apt pkg=git state=installed

  - name: Oh-My-Zsh
    action: git repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/$user/.oh-my-zsh    
