---
- hosts: all
  vars:
    - user: goncalo  

  tasks:
  - name: Add user
    action: user name=$user

  - name: Add authorized key
    action: authorized_key user=$user key='$FILE(config/id_rsa.pub)'
  
  - name: Add user to sudoers
    action: lineinfile dest=/etc/sudoers regexp="$user ALL" line="$user ALL=(ALL) NOPASSWD:ALL" state=present

  - name: Install vim
    action: apt pkg=vim state=installed

  - name: Install zsh
    action: apt pkg=zsh state=installed

  - name: Install ruby
    action: apt pkg=ruby state=installed

  - name: Install rubygems
    action: apt pkg=rubygems state=installed

  - name: Install homesick
    action: gem name=homesick state=latest
      

