  - name: Update APT package cache
    action: apt update_cache=yes
 
  - name: Upgrade APT to the lastest packages
    action: apt upgrade=dist
 
  - name: Install unattended-upgrades
    action: apt pkg=unattended-upgrades state=present
 
  - name: Adjust APT update intervals
    action: copy src=$files_path/apt_periodic dest=/etc/apt/apt.conf.d/10periodic
 
  - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
    action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent
